/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.temelt.coursemgmt.gui.kullanici;

import com.temelt.coursemgmt.model.kullanici.Kullanici;
import com.temelt.coursemgmt.service.kullanici.KullaniciService;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vektorel
 */
public class frmKullanici extends javax.swing.JDialog {

    KullaniciService kullaniciService = new KullaniciService();

    /**
     * Creates new form frmKullanici
     */
    public frmKullanici(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        tabloDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKullanici = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuYeni = new javax.swing.JMenuItem();
        mnuGuncelle = new javax.swing.JMenuItem();
        mnuSil = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblKullanici.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKullanici);

        jMenu1.setText("Kullanıcı");

        mnuYeni.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        mnuYeni.setText("Yeni");
        mnuYeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuYeniActionPerformed(evt);
            }
        });
        jMenu1.add(mnuYeni);

        mnuGuncelle.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F6, 0));
        mnuGuncelle.setText("Güncelle");
        mnuGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuncelleActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGuncelle);

        mnuSil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F7, 0));
        mnuSil.setText("Sil");
        mnuSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSilActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSil);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuYeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuYeniActionPerformed
        frmKullaniciEkleGuncelle ekleGuncelle = new frmKullaniciEkleGuncelle(null, true);
        ekleGuncelle.show();
        tabloDoldur();
    }//GEN-LAST:event_mnuYeniActionPerformed

    private void mnuGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuncelleActionPerformed


    }//GEN-LAST:event_mnuGuncelleActionPerformed

    private void mnuSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSilActionPerformed


    }//GEN-LAST:event_mnuSilActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnuGuncelle;
    private javax.swing.JMenuItem mnuSil;
    private javax.swing.JMenuItem mnuYeni;
    private javax.swing.JTable tblKullanici;
    // End of variables declaration//GEN-END:variables

    private void tabloDoldur() {
        List<Kullanici> liste = kullaniciService.getAll();
        String[][] data = new String[liste.size()][7];
        for (int i = 0; i < liste.size(); i++) {
            data[i][0] = liste.get(i).getId().toString();
            data[i][1] = liste.get(i).getKullaniciAdi();
            data[i][2] = liste.get(i).getAd();
            data[i][3] = liste.get(i).getSoyad();
            data[i][4] = liste.get(i).getEmail();
            if(liste.get(i).getUyelikTarihi()!=null)
                data[i][5] = liste.get(i).getUyelikTarihi().toString();
            if (liste.get(i).getRol() != null) {
                data[i][6] = liste.get(i).getRol().name();
            }
        }
        tblKullanici.setModel(new DefaultTableModel(data,
                new String[]{"Id", "Kullanıcı Adı", "Adı",
                    "Soyadı", "Email", "Üyelik Tarihi", "Rol"}));
    }
}
