/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.temelt.coursemgmt.gui;

import com.temelt.coursemgmt.gui.demirbas.frmDemirbas;
import com.temelt.coursemgmt.gui.ik.frmIK;
import com.temelt.coursemgmt.gui.kullanici.frmKullanici;
import com.temelt.coursemgmt.gui.muhasebe.frmMuhasebeGelir;
import com.temelt.coursemgmt.gui.muhasebe.frmMuhasebeEkranSec;
import com.temelt.coursemgmt.gui.ogrenciisleri.frmOgrenciIsleri;
import com.temelt.coursemgmt.gui.ogretmen.frmOgretmen;
import com.temelt.coursemgmt.gui.yonetim.frmYonetim;
import com.temelt.coursemgmt.model.kullanici.Kullanici;

/**
 *
 * @author vektorel
 */
public class frmAnaSayfa extends javax.swing.JFrame {

    Kullanici kullanici;

    /**
     * Creates new form frmAnaSayfa
     */
    public frmAnaSayfa(Kullanici kullanici) {
        initComponents();
        setLocationRelativeTo(null);
        this.kullanici = kullanici;
        lblMesaj.setText("Hoşgeldiniz " + kullanici.getAd() + " " + kullanici.getSoyad());
        rolleriUygula();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKullanici = new javax.swing.JButton();
        btnIK = new javax.swing.JButton();
        btnMuhasebe = new javax.swing.JButton();
        btnOgrenci = new javax.swing.JButton();
        btnOgretmen = new javax.swing.JButton();
        btnDemirbas = new javax.swing.JButton();
        btnYonetim = new javax.swing.JButton();
        lblMesaj = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKullanici.setText("Kullanıcı İşlemleri");
        btnKullanici.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciActionPerformed(evt);
            }
        });

        btnIK.setText("IK İşlemleri");
        btnIK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIKActionPerformed(evt);
            }
        });

        btnMuhasebe.setText("Muhasebe İşlemleri");
        btnMuhasebe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMuhasebeActionPerformed(evt);
            }
        });

        btnOgrenci.setText("Öğrenci İşleri");
        btnOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgrenciActionPerformed(evt);
            }
        });

        btnOgretmen.setText("Öğretmen İşlemleri");
        btnOgretmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOgretmenActionPerformed(evt);
            }
        });

        btnDemirbas.setText("Demirbaş İşlemleri");
        btnDemirbas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemirbasActionPerformed(evt);
            }
        });

        btnYonetim.setText("Yönetim İşlemleri");
        btnYonetim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYonetimActionPerformed(evt);
            }
        });

        lblMesaj.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblMesaj.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 31, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnYonetim)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOgrenci, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKullanici, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMuhasebe, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDemirbas, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnOgretmen, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(lblMesaj)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKullanici, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDemirbas, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIK, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMuhasebe, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOgretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(btnYonetim, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKullaniciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciActionPerformed

        frmKullanici kullanici = new frmKullanici(null, true);
        kullanici.show();
    }//GEN-LAST:event_btnKullaniciActionPerformed

    private void btnDemirbasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemirbasActionPerformed
        frmDemirbas demirbas = new frmDemirbas(null, true);
        demirbas.show();
    }//GEN-LAST:event_btnDemirbasActionPerformed

    private void btnIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIKActionPerformed
        frmIK ik = new frmIK(null, true);
        ik.show();
    }//GEN-LAST:event_btnIKActionPerformed

    private void btnMuhasebeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMuhasebeActionPerformed
        frmMuhasebeEkranSec ekranSec = new frmMuhasebeEkranSec(null, true);
        ekranSec.show();
    }//GEN-LAST:event_btnMuhasebeActionPerformed

    private void btnOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgrenciActionPerformed
        frmOgrenciIsleri ogrenciIsleri = new frmOgrenciIsleri(null, true);
        ogrenciIsleri.show();
    }//GEN-LAST:event_btnOgrenciActionPerformed

    private void btnOgretmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOgretmenActionPerformed
        frmOgretmen ogretmen = new frmOgretmen(null, true);
        ogretmen.show();
    }//GEN-LAST:event_btnOgretmenActionPerformed

    private void btnYonetimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYonetimActionPerformed
        frmYonetim yonetim = new frmYonetim(null, true);
        yonetim.show();
    }//GEN-LAST:event_btnYonetimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDemirbas;
    private javax.swing.JButton btnIK;
    private javax.swing.JButton btnKullanici;
    private javax.swing.JButton btnMuhasebe;
    private javax.swing.JButton btnOgrenci;
    private javax.swing.JButton btnOgretmen;
    private javax.swing.JButton btnYonetim;
    private javax.swing.JLabel lblMesaj;
    // End of variables declaration//GEN-END:variables

    private void rolleriUygula() {
        switch(this.kullanici.getRol()){
               case MUHASEBE:
                btnDemirbas.setVisible(false);
                btnYonetim.setVisible(false);
                btnIK.setVisible(false);
                btnKullanici.setVisible(false);
                btnOgrenci.setVisible(false);
                btnOgretmen.setVisible(false);
                break;
            case IK:
                btnDemirbas.setVisible(false);
                btnYonetim.setVisible(false);
                btnMuhasebe.setVisible(false);
                btnKullanici.setVisible(false);
                btnOgrenci.setVisible(false);
                btnOgretmen.setVisible(false);
                break;
            case DEMIRBAS:
                btnIK.setVisible(false);
                btnYonetim.setVisible(false);
                btnMuhasebe.setVisible(false);
                btnKullanici.setVisible(false);
                btnOgrenci.setVisible(false);
                btnOgretmen.setVisible(false);
                break;
            case OGRENCI_ISLERI:
                btnDemirbas.setVisible(false);
                btnYonetim.setVisible(false);
                btnMuhasebe.setVisible(false);
                btnKullanici.setVisible(false);
                btnIK.setVisible(false);
                btnOgretmen.setVisible(false);
                break;
            
        }
    }
}
