/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.temelt.coursemgmt.gui.muhasebe;

import static com.temelt.coursemgmt.gui.muhasebe.frmMuhasebeGider.clickValue;
import com.temelt.coursemgmt.model.muhasebe.Gider;
import com.temelt.coursemgmt.service.muhasebe.GiderService;
import java.util.List;

/**
 *
 * @author Master
 */
public class giderSilPop extends javax.swing.JDialog {
GiderService giderService = new GiderService();
    /**
     * Creates new form giderSilPop
     */
    public giderSilPop(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        get();
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5miktar = new javax.swing.JLabel();
        jLabel6ogretmenid = new javax.swing.JLabel();
        jLabel7konu = new javax.swing.JLabel();
        jLabel8tarih = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10personelid = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6envanterid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel3.setText("Konu   :");

        jLabel4.setText("Tarih    :");

        jLabel5miktar.setText("jLabel5");

        jLabel6ogretmenid.setText("jLabel6");

        jLabel7konu.setText("jLabel7");

        jLabel8tarih.setText("jLabel8");

        jButton1.setText("sil");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("personel id :");

        jLabel10personelid.setText("jLabel10");

        jLabel1.setText("Miktar  :");

        jLabel2.setText("Ogretmen   :");

        jLabel5.setText("Envanter :");

        jLabel6envanterid.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8tarih)
                            .addComponent(jLabel7konu)
                            .addComponent(jLabel5miktar)
                            .addComponent(jLabel10personelid)
                            .addComponent(jLabel6ogretmenid)
                            .addComponent(jLabel6envanterid))))
                .addContainerGap(142, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6envanterid))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel5miktar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6ogretmenid))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10personelid))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7konu))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8tarih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GiderService giderService = new GiderService();
        List<Gider> list = giderService.getByIdd( Long.parseLong(clickValue) );
        giderService.delete(list.get(0));
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_formWindowClosing
public void get() {
        
        List<Gider> list = giderService.getByIdd(Long.parseLong(clickValue));

        jLabel5miktar.setText(String.valueOf(list.get(0).getEnvanter()));
        jLabel7konu.setText(list.get(0).getKonu());
        jLabel10personelid.setText(String.valueOf(list.get(0).getPersonel()));
        jLabel6ogretmenid.setText(String.valueOf(list.get(0).getOgretmen()));
        jLabel6envanterid.setText(String.valueOf(list.get(0).getMiktar()));
        jLabel8tarih.setText(String.valueOf(list.get(0).getTarih()));
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10personelid;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel5miktar;
    private javax.swing.JLabel jLabel6envanterid;
    private javax.swing.JLabel jLabel6ogretmenid;
    private javax.swing.JLabel jLabel7konu;
    private javax.swing.JLabel jLabel8tarih;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
