/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.temelt.coursemgmt.gui.muhasebe;

import static com.temelt.coursemgmt.gui.muhasebe.frmMuhasebeGider.clickValue;
import com.temelt.coursemgmt.model.muhasebe.Gider;
import com.temelt.coursemgmt.service.muhasebe.GiderService;
import java.math.BigDecimal;
import java.util.List;

/**
 *
 * @author Master
 */
public class giderGuncellePop extends javax.swing.JDialog {

    GiderService giderService = new GiderService();

    /**
     * Creates new form giderGuncellePop
     */
    public giderGuncellePop(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        get();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextField1miktar = new javax.swing.JTextField();
        jTextField6konu = new javax.swing.JTextField();
        jLabel6envanter = new javax.swing.JLabel();
        jLabel6ogretmen = new javax.swing.JLabel();
        jLabel6personel = new javax.swing.JLabel();
        jLabel6tarih = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Miktar  :");

        jLabel2.setText("Ogretmen   :");

        jLabel3.setText("Konu   :");

        jLabel5.setText("Envanter :");

        jLabel4.setText("Tarih    :");

        jButton1.setText("Guncelle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("personel id :");

        jLabel6envanter.setText("jLabel6");

        jLabel6ogretmen.setText("jLabel6");

        jLabel6personel.setText("jLabel6");

        jLabel6tarih.setText("jLabel6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1miktar)
                            .addComponent(jLabel6envanter, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6konu)
                            .addComponent(jLabel6ogretmen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6personel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6tarih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(124, 124, 124))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1miktar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6envanter))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6ogretmen))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6personel))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField6konu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6tarih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GiderService giderService = new GiderService();
        List<Gider> list = giderService.getByIdd(Long.parseLong(clickValue));
        Gider g = new Gider();
        BigDecimal money = new BigDecimal(jTextField1miktar.getText().replaceAll(",", ""));
        
        
        g.setId(Long.parseLong(clickValue));
        g.setKonu(jTextField6konu.getText());
        g.setMiktar(money);
        g.setOgretmen(list.get(0).getOgretmen());
        g.setTarih(list.get(0).getTarih());
        g.setEnvanter(list.get(0).getEnvanter());
        giderService.update(g);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    public void get() {

        List<Gider> list = giderService.getByIdd(Long.parseLong(clickValue));

        jTextField1miktar.setText(String.valueOf(list.get(0).getMiktar()));
        jTextField6konu.setText(list.get(0).getKonu());
        jLabel6personel.setText(String.valueOf(list.get(0).getPersonel()));
        jLabel6ogretmen.setText(String.valueOf(list.get(0).getOgretmen()));
        jLabel6envanter.setText(String.valueOf(list.get(0).getEnvanter()));
        jLabel6tarih.setText(String.valueOf(list.get(0).getTarih()));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6envanter;
    private javax.swing.JLabel jLabel6ogretmen;
    private javax.swing.JLabel jLabel6personel;
    private javax.swing.JLabel jLabel6tarih;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1miktar;
    private javax.swing.JTextField jTextField6konu;
    // End of variables declaration//GEN-END:variables
}
