/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.temelt.coursemgmt.gui.ik;

import com.temelt.coursemgmt.model.ik.Ogretmen;
import com.temelt.coursemgmt.service.ik.OgretmenService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class FrmOgretmen extends javax.swing.JDialog {

    public static String valueInCell;

    JPopupMenu popupMenu = new JPopupMenu();
    JMenuItem menuItemAdd = new JMenuItem("Kişi Ekle");
    JMenuItem menuItemDelete = new JMenuItem("Kişi Sil");
    JMenuItem menuItemUpdate = new JMenuItem("Kişi Güncelle");

    /**
     * Creates new form FrmOgretmen
     */
    public FrmOgretmen(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        OgretmentabloDoldur();
        popupMenuEkle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblOgretmen = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblOgretmen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblOgretmen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOgretmenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOgretmen);

        jMenu1.setText("İşlemler");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem1.setText("Çıkış");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tblOgretmenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOgretmenMouseClicked
        int row = tblOgretmen.rowAtPoint(evt.getPoint());
        int col = tblOgretmen.columnAtPoint(evt.getPoint());
        valueInCell = (String) tblOgretmen.getValueAt(row, 0);
    }//GEN-LAST:event_tblOgretmenMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOgretmen;
    // End of variables declaration//GEN-END:variables

    private void OgretmentabloDoldur() {
        List<Ogretmen> oList = OgretmenService.baseService.getAll(Ogretmen.class);
        String[][] data = new String[oList.size()][7];

        for (int i = 0; i < oList.size(); i++) {

            data[i][0] = oList.get(i).getId().toString();
            data[i][1] = oList.get(i).getAd();
            data[i][2] = oList.get(i).getSoyad();
            data[i][3] = oList.get(i).getTel();
            data[i][4] = oList.get(i).getMail();
            data[i][5] = oList.get(i).getAdres();
            data[i][6] = String.valueOf(oList.get(i).getKayitTarihi());

        }
        tblOgretmen.setModel(new DefaultTableModel(data, new String[]{"No", "Ad", "Soyad", "Telefon", "Email", "Adres"}));

    }

    private void popupMenuEkle() {
        popupMenu.add(menuItemAdd);
        menuItemAdd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FrmOgretmenEkle isci = new FrmOgretmenEkle(null, true);
                isci.show();
                OgretmentabloDoldur();
            }
        });
        popupMenu.add(menuItemUpdate);
        menuItemUpdate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int indexOfSelectedItem = tblOgretmen.getSelectedRow();
                if (indexOfSelectedItem != -1) {
                    Long id = Long.parseLong(tblOgretmen.getValueAt(indexOfSelectedItem, 0).toString());
                    OgretmenService os = new OgretmenService();
                    Ogretmen o = os.getById(id);
                    FrmOgretmenGuncelleme guncel = new FrmOgretmenGuncelleme(null, true);
                    guncel.show();
                    OgretmentabloDoldur();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Lütfen Kayıt Seçiniz!");
                }
            }
        });

        popupMenu.add(menuItemDelete);
        menuItemDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int indexOfSelectedItem = tblOgretmen.getSelectedRow();
                if (indexOfSelectedItem != -1) {
                    Long id = Long.parseLong(tblOgretmen.getValueAt(indexOfSelectedItem, 0).toString());
                    OgretmenService os = new OgretmenService();
                    Ogretmen o = os.getById(id);
                    FrmOgretmnSil sil = new FrmOgretmnSil(null, true, o);
                    sil.show();
                    OgretmentabloDoldur();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Lütfen Kayıt Seçiniz!");
                }
            }
        });

        tblOgretmen.setComponentPopupMenu(popupMenu);
    }

}
