/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.temelt.coursemgmt.gui.ik;

import com.temelt.coursemgmt.model.ik.Ogretmen;
import com.temelt.coursemgmt.model.ik.Personel;
import com.temelt.coursemgmt.service.ik.OgretmenService;
import com.temelt.coursemgmt.service.ik.PersonelService;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class FrmPersonel extends javax.swing.JDialog {

    public static String valueInCell;

    JPopupMenu popupMenu = new JPopupMenu();
    JMenuItem menuItemAdd = new JMenuItem("Kişi Ekle");
    JMenuItem menuItemDelete = new JMenuItem("Kişi Sil");
    JMenuItem menuItemUpdate = new JMenuItem("Kişi Güncelle");

    /**
     * Creates new form FrmPersonel
     */
    public FrmPersonel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        PersoneltabloDoldur();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonel = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblPersonel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPersonel);

        jMenu1.setText("İşlemler");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F8, 0));
        jMenuItem1.setText("Çıkış");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 4, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
        this.dispose();
    }//GEN-LAST:event_jMenuItem1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPersonel;
    // End of variables declaration//GEN-END:variables

    private void PersoneltabloDoldur() {
        List<Personel> pList = PersonelService.baseService.getAll(Personel.class);
        String[][] data = new String[pList.size()][7];

        for (int i = 0; i < pList.size(); i++) {
            data[i][0] = pList.get(i).getId().toString();
            data[i][1] = pList.get(i).getAd();
            data[i][2] = pList.get(i).getSoyad();
            data[i][3] = pList.get(i).getTel();
            data[i][4] = pList.get(i).getMail();
            data[i][5] = pList.get(i).getAdres();
            data[i][6] = String.valueOf(pList.get(i).getBaslamaTarihi());

        }
        tblPersonel.setModel(new DefaultTableModel(data, new String[]{"No", "Ad", "Soyad", "Telefon", "Email", "Adres"}));

    }
    
    private void popupMenuEkle() {
        popupMenu.add(menuItemAdd);
        menuItemAdd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                FrmPersonelEkle isci = new FrmPersonelEkle(null, true);
                isci.show();
                PersoneltabloDoldur();
            }
        });
        popupMenu.add(menuItemUpdate);
        menuItemUpdate.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int indexOfSelectedItem = tblPersonel.getSelectedRow();
                if (indexOfSelectedItem != -1) {
                    Long id = Long.parseLong(tblPersonel.getValueAt(indexOfSelectedItem, 0).toString());
                    PersonelService ps = new PersonelService();
                    Personel p = ps.getById(id);
                    FrmPersonelGuncelle guncel = new FrmPersonelGuncelle(null, true);
                    guncel.show();
                    PersoneltabloDoldur();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Lütfen Kayıt Seçiniz!");
                }
            }
        });

        popupMenu.add(menuItemDelete);
        menuItemDelete.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int indexOfSelectedItem = tblPersonel.getSelectedRow();
                if (indexOfSelectedItem != -1) {
                    Long id = Long.parseLong(tblPersonel.getValueAt(indexOfSelectedItem, 0).toString());
                    PersonelService ps = new PersonelService();
                    Personel p = ps.getById(id);
                    FrmPersonelSil sil = new FrmPersonelSil(null, true, p);
                    sil.show();
                    PersoneltabloDoldur();

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Lütfen Kayıt Seçiniz!");
                }
            }
        });

        tblPersonel.setComponentPopupMenu(popupMenu);
    }
}
